### ISSUE TITLE
`Settings.login_session_timeout` default not being set

### ISSUE THREAD

**Issue by jmkrm** [pglombardo/PasswordPusher#3122]
We are running the official Docker Image together with a MariaDB database in another container (mariadb:latest). 

When we upgrade the pwpush Image from 1.51.4 to 1.51.5 using the latest tag, the DB upgrade fails and the application crashes.

```
/usr/local/bin/bundle:25:in 'Kernel#load'
/usr/local/bin/bundle:25:in '<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
Password Pusher Version: 1.51.5

According to DATABASE_URL database backend is set to mysql2:...

Password Pusher: migrating database to latest...
rake aborted!
NoMethodError: undefined method 'downcase' for nil (NoMethodError)

  config.timeout_in = Settings.login_session_timeout.to_s.strip.split(" ").then { |n, u| n.to_i.send(u.downcase.to_sym) }
                                                                                                      ^^^^^^^^^
/opt/PasswordPusher/config/initializers/devise.rb:194:in 'block (2 levels) in <main>'

```

Switching back to the 1.51.4 Image resolves this issue, which is the workaround we are currently using.

**Comment by justinkruit** [comment]
Came here to report the same.

**Comment by tol0** [comment]
Same here with postgresql.

**Comment by pglombardo** [comment]
Thanks for reporting all/apologies for the issue.

`Settings.login_session_timeout` is a new setting in `config/settings.yml` with a default set in `config/defaults/settings.yml`.

I just booted a vanilla v1.51.5 and one with logins enabled and they booted without issue:

![Image](https://github.com/user-attachments/assets/f18c939e-5117-41f2-bc40-7954655f1041)
![Image](https://github.com/user-attachments/assets/d9fc3e97-1842-4e04-8b09-8e7c85c4323e)

Do you guys have the the defaults file in your containers?  `/opt/PasswordPusher/config/defaults/settings.yml`?

I believe this is happening because somehow the default isn't being set.  

If you want a quick work-around, you could simply set `PWP__LOGIN_SESSION_TIMEOUT='2 hours'` but things might break again the next time I add another config option.

**Comment by tol0** [comment]
I have to set 
`login_session_timeout: '2 hours'
`
in my settings.yml, then I was able to start the container. And yes, defaults file is in place:

```
fd91fb13a0e6:/$ cat /opt/PasswordPusher/config/defaults/settings.yml | grep SESSION_TIMEOUT
# PWP__LOGIN_SESSION_TIMEOUT='2 hours'
```

**Comment by pglombardo** [comment]
That default should have been set in the `config/defaults/settings.yml` file for you.  I'm not sure why not but glad that it's working.

**Comment by bigbeka** [comment]
Adding `login_session_timeout: '2 hours'` to my `/opt/PasswordPusher/config/settings.yml` (not default) helped. 

@pglombardo could the issue be with read/write permissions?

**Comment by pglombardo** [comment]
> could the issue be with read/write permissions?

I wouldn't think so but might be possible.  My original thought was that some might have a docker mount that hides the `config/defaults/` directory.

Before `config/settings.yml` and environment variables are loaded, we load that defaults file first [here](https://github.com/pglombardo/PasswordPusher/blob/master/config/initializers/settings.rb#L32-L33).

```ruby
# Prepend defaults to the Settings object in case users are missing some of the latest settings
Settings.prepend_source!(Rails.root.join("config/defaults/settings.yml").to_s)
```

**Comment by pglombardo** [comment]
Hi @MaxAnderson95 - that's the right idea but the defaults (`config/defaults/settings.yml`) are loaded first to pre-populate all settings (even new settings) and then the user settings (`config/settings.yml` and env vars) are loaded to override the loaded defaults.

This is the way it has always worked in the past.  Maybe something has broke - I'll look again soon.

**Comment by jmkrm** [comment]
OP here, I also managed to get it running by adding `login_session_timeout: '2 hours'`  to my settings.yml

The default settings.yml is also present in my container, but I noticed one little detail:

The default file contains `login_session_timeout: "2 hours"` with double quotation marks. Every other setting in the file is using single quotation marks.

I'm no Ruby expert, so this is just a shot in the dark.

**Comment by pglombardo** [comment]
Thanks @jmkrm - that's a fair theory but after a bit of testing/debugging, it actually was because of initialization order of the `Settings` object.  Fix incoming.

**Comment by pglombardo** [comment]
Thanks for the patience all - I believe this is now fixed in [v1.51.13](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.51.13).  Could you confirm and let me know?

**Comment by jmkrm** [comment]
@pglombardo I've removed `login_session_timeout: '2 hours'` from the settings.yml file and updated to the latest version, working perfectly fine for me now! Thanks!

**Comment by pglombardo** [comment]
Hi all - I believe this issue is now fixed.  Thanks all for the help and input.  I'll close it out but ping me if anything remains!
